version: '3.8'

services:
  nginx1:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./var/www/html:/usr/share/nginx/html
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1

  nginx2:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./var/www/html:/usr/share/nginx/html
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2

  php1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./var/www/html:/var/www/html
    depends_on:
      - mysql
    command: /app/initsql.sh

  php2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./var/www/html:/var/www/html
    depends_on:
      - mysql
    command: /app/initsql.sh

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      DB_DATABASE: laraveldb
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
